### ISSUE TITLE
Falsche Bezeichnung in der Effektauswahl

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/media_srcset#11]
Der Effekt wird als "Bild skalieren" gelistet

![bildschirmfoto 2018-01-08 um 16 11 09](https://user-images.githubusercontent.com/791247/34676953-da750322-f48e-11e7-9aeb-a293231e3d3b.png)

**Comment by joachimdoerr** [comment]
Was wäre hier ein gutes Naming? "Bild: Skalieren mit srcset"?

**Comment by skerbis** [comment]
SRCSET generieren vielleicht?

**Comment by joachimdoerr** [comment]
Ja aber es skaliert ja auch.

**Comment by skerbis** [comment]
Ja natürlich, aber das sollte ein srcset ja auch tun - oder?

**Comment by joachimdoerr** [comment]
Also eigentlich wird schon ein SRCSET titel geschreiben: https://github.com/FriendsOfREDAXO/media_srcset/blob/13705cdf6545811ca2b4352bab44cd26141eb6a4/lib/effects/effect_srcset.php#L27
Merkwürdig!

**Comment by skerbis** [comment]
findet sich nicht in der lang-Datei

**Comment by joachimdoerr** [comment]
4b73c3057a99e8ba4a5d0c002a67ac6a559dedc3

Sollte nun gefixt sein.

**Comment by skerbis** [comment]
Super
