### ISSUE TITLE
Trenner "__" haben probleme mit MediaManager

### ISSUE THREAD

**Issue by darwin26** [FriendsOfREDAXO/media_srcset#12]
Hi,
scheinbar gibt es Probleme mit den Unterstrichen (Bsp: "__600") ab dem MediaManager 2.5.3 (oder evtl schon früher). Wenn man die Unterstriche gegen "-" austauscht, können die ImageTypes mit derm angewendeten Effekt auch wieder erzeugt bzw. einzeln per URL aufgerufen werden ...

test:
lokal / MAMP
php 7.0.12
rex 5.5.1
FireFox 58.0.2 (MacOSX)

**Comment by joachimdoerr** [comment]
@darwin26 ich kann das nicht bestätigen. Kannst du das nochmals prüfen?
