### ISSUE TITLE
ErrorException in rex_effect_srcset

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/media_srcset#13]
Bekomme plötzlich den hier:

```
ErrorException (E_ERROR)
Class rex_effect_srcset contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (rex_effect_abstract::execute)
 
Stack frames (1)
0
ErrorException 
…/redaxo/src/addons/media_manager/lib/effects/effect_srcset.php69
```

**Comment by cukabeka** [comment]
Fürs Backlog: Hier findet sich der Teil, bei dem die notwendigen Methoden fehlen:
https://github.com/FriendsOfREDAXO/media_srcset/blob/master/lib/effects/effect_srcset.php#L9-L27

**Comment by joachimdoerr** [comment]
sollte nun laufen. es gibt nur eine abstract method und diese ist vorhanden im parend resize.
