### ISSUE TITLE
Error: open_basedir restriction

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/media_srcset#14]
file_exists() [<a href='https://php.net/manual/function.file-exists'>function.file-exists</a>]: open_basedir restriction in effect. File(/) is not within the allowed path(s): (/var/www/vhosts/domain.de/:/tmp/)

**Comment by mhut47** [comment]
Ich bekomme den Fehler auch. Update -> REDAXO 5.2 zu 5.6.5, kann hier jemand helfen?

**Comment by joachimdoerr** [comment]
Ich kann das Problem nicht nachstellen.

**Comment by skerbis** [comment]
@mhut47 bitte testen
