### ISSUE TITLE
Fehlerhafte Bilder URLs

### ISSUE THREAD

**Issue by godsdog** [FriendsOfREDAXO/media_srcset#16]
Bei mir werden die SRCSET Bild URLs falsch generiert. YRewrite ist aktiv.
Es werden die Bilder wie folgt ausgegeben:

`<img src="index.php?rex_media_type=tinymce&rex_media_file=logo.png" srcset="/unterordner/images/tinymce__400/index.php?rex_media_type=tinymce&logo.png 480w, /unterordner/images/tinymce__700/index.php?rex_media_type=tinymce&logo.png 768w, /unterordner/images/tinymce__800/index.php?rex_media_type=tinymce&logo.png 960w" />`

`/unterordner/images/tinymce__400/index.php?rex_media_type=tinymce&logo.png`
müsste so aussehen:
`/unterordner/mediatypes/tinymce__400/logo.png`

Die URLs stimmen so nicht.

Redaxo: 5.5.1 im Unterordner

**Comment by joachimdoerr** [comment]
f06e2b1f6f5f99c44fd7a5728000103867a5c158
17f5a62f53fb34fbecd71c56ca5bea7da76ec486

@godsdog  Bitte testen.

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/media_srcset/issues/18

**Comment by godsdog** [comment]
Jo läuft nun! Vielen Dank!
