### ISSUE TITLE
Urls mit mediamanager Methode erzeugen

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/media_srcset#18]
Siehe : https://redaxo.org/doku/master/media-manager#url

https://github.com/FriendsOfREDAXO/media_srcset/blob/13705cdf6545811ca2b4352bab44cd26141eb6a4/lib/srcset.php#L356

/images/ ist deprecated
https://github.com/FriendsOfREDAXO/media_srcset/blob/13705cdf6545811ca2b4352bab44cd26141eb6a4/lib/srcset.php#L351

**Comment by joachimdoerr** [comment]
20df82def8fada762e94d6341e15fe409bc0525f

**Comment by joachimdoerr** [comment]
5107d59c512a9096b9de9ae96d85d379bcaafc08
