### ISSUE TITLE
<picture> funktioniert nicht

### ISSUE THREAD

**Issue by ansichtsache** [FriendsOfREDAXO/media_srcset#19]
anscheinend gibt es eine falsche ausgabe bei der picture funktion.
Meine Eingabe im Modul:

```
<picture>
<source media="(min-width: 480w)" srcset="rex_media_type=content">
<source media="(min-width: 550w)" srcset="rex_media_type=content">
<source media="(min-width: 768w)" srcset="rex_media_type=content">
<img src="'.rex_media_manager::getUrl('content', 'REX_MEDIA[1]').'" alt="">
</picture>
```

Genriert folgende Ausgabe:
```
<picture>    
<source media="(min-width: 480w)" srcset="/media/content__440/image.png 480w, /media/content__500/image.png 550w, /media/content__700/image.png 768w">
<source media="(min-width: 768w)" srcset="/media/content__440/image.png 480w, /media/content__500/image.png 550w, /media/content__700/image.png 768w">
<img src="index.php?rex_media_type=content&amp;rex_media_file=image.png" alt=""></picture>
```

sollte es nicht ausgeben:
```
<picture>    
<source media="(min-width: 480w)" srcset="/media/content__440/image.png 480w">
<source media="(min-width: 768w)" srcset="/media/content__700/image.png 768w">
<img src="index.php?rex_media_type=content&amp;rex_media_file=image.png" alt="">
</picture>
```
?

**Comment by skerbis** [comment]
@ansichtsache du hast 3 Mal den selben MediaManager-Typ verwendet. ..

**Comment by ansichtsache** [comment]
@skerbis dann verstehe ich möglicherweise die anwendung nicht?

bei img wird ja aus dem code im modul
```<img src="'.rex_media_manager::getUrl('content', 'REX_MEDIA[2]').'" srcset="rex_media_type=content" />```

folgender code ausgegeben:
```<img src="/media/content/image.png" srcset="/media/content__440/image.png 480w, /media/content__500/image.png 550w, /media/content__700/image.png 768w">```

das heißt, für img reicht die eingabe der unterschiedlichen größen im effekt (content) des media managers und für picture müsste ich die unterschiedlichen größen als eigene effekte (content_440, content_550, content_700) anlegen?

**Comment by skerbis** [comment]
Ja, da die Effekte sich ja unterscheiden können - Beispiele: . portrait , landscape - Darstellung. 
Das Picture-Tag kann ja mehr als nur die Bilder in gewissen Gößen ausliefern. Soweit ich das verstehe.

**Comment by ansichtsache** [comment]
ahh, ok. also bei verwendung von picture jeweils effekt anlegen mit srcset und dann jeweils nur die entsprechende anweisung ```440 480w```, etc. 
bei img reicht ja ein effekt mit der anweisung ```440 480w, 500 550w, 700 768w``` …

eingabe dann:
```<picture>
<source media="(min-width: 480w)" srcset="rex_media_type=content_440">
<source media="(min-width: 550w)" srcset="rex_media_type=content_500">
<source media="(min-width: 768w)" srcset="rex_media_type=content_700">
<img src="'.rex_media_manager::getUrl('content', 'REX_MEDIA[1]').'" alt="">
</picture>```

dann ist für picture die alternative Mediamanager Plus vielleicht besser geeignet?

**Comment by skerbis** [comment]
Bei dieser Variante brauchst du das AddOn schon garnicht. 
Ist halt davon abhängig was genau passieren soll. Hier kannst du es halt fein steuern. So kannst du halt für die viewports immer noch die verschiedenen Auflösungen (z.B. retina) im srcset ausliefern.

**Comment by ansichtsache** [comment]
du meinst für die variante brauche ich das picture element nicht und bin mit dem img gut bedient?

und ja, mehr kontrolle, mehr hirnschmalz notwendig ;–)

**Comment by skerbis** [comment]
Nein, ich meine, dass du das Picture-Tag dann auch traditionell bauen kannst, wenn du schon 3 Effekte brauchst. (Das img tag ist übrigens nicht responsive) es richtet sich an die initiale Auflösung und Fenstergröße. Bei einem Resize passiert nix.

**Comment by hirbod** [comment]
Ich hatte auch Probleme mit Picture (wenn es mehr als eine auf der Seite gab).
#25 fixed das Problem
