### ISSUE TITLE
sizes Attribut

### ISSUE THREAD

**Issue by IngoWinter** [FriendsOfREDAXO/media_srcset#22]
Hat es einen Grund, dass ich kein sizes Attribut im Effekt definieren kann? Oder hat das bloss noch keiner gebraucht? Wenn letzteres, würde ich mir das auf die ToDo Liste setzen.

**Comment by michael-kreatif** [comment]
+1, für W3C HTML Validator ist das fehlende sizes Attribut ein Fehler.

**Comment by cukabeka** [comment]
habe auch gerade das responsive image linter plugin in Chrome benutzt und diesen fehler bekommen:

> Sizes attribute must be set if W descriptors are used
> Descriptors 150w, 600w, 900w, 1200w, 1500w are used but the sizes attribute is missing.
> 
> Try using sizes="150px"
> 
> <img
> 	class="text-content-bild type"
> 	src="/media/type/image.jpg"
> 	srcset="
> 		/media/type__150/image.jpg 150w,
> 		/media/type__600/image.jpg 600w,
> 		/media/type__900/image.jpg 900w,
> 		/media/type__1200/image.jpg 1200w,
> 		/media/type__1500/image.jpg 1500w
> 	"
> 	width="150"
> 	height="213"
> 	alt=""
> >

reicht es aber nicht, wenn das sizes attribut automatisch mit den angegebenen w-Zahlen ergänzt wird? Hilft es, manuell da etwas anderes anzugeben?

**Comment by cukabeka** [comment]
SIehe PR dazu - braucht aber Review bzw Euren Input
