### ISSUE TITLE
srcset an anderen Stellen einbinden

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/media_srcset#23]
srcset wäre (als data-srcset) zum Beispiel für Fancybox interessant.
Eine Idee wäre rex_media zu erweitern
`rex_media::get($file)->getSrcset(imgType)`

**Comment by skerbis** [comment]
data-srcset kann man bereits verwenden

**Comment by marcohanke** [comment]
@skerbis Hier nochmal aus gegebenem Anlass.
ein data-srcset in einem a Tag für Fancybox wäre fein.

**Comment by eaCe** [comment]
`rex_media_srcset::getSrcSet('redaxo.jpg', 'content');`
