### ISSUE TITLE
not_enlarge wird nicht beachtet

### ISSUE THREAD

**Issue by hirbod** [FriendsOfREDAXO/media_srcset#26]
Auch wenns Sinn macht die gewünschte Breite wie notiert auszuliefern, not_enlarge sollte nicht ignoriert werden, wenn es gesetzt ist, da es teilweise bei schlechter Quelldatei durchaus zu JPG Artefaktmatsch kommen kann, wenn zu kleine Bilder überskaliert werden.

Wir sollten die not_enlarge Methoden vom Original resize-effekt übernehmen.

**Comment by AWqxKAWERbXo** [comment]
Laut #29 war Reproduktion nicht möglich.
