### ISSUE TITLE
Undefined index: height

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/media_srcset#28]
Nach langer Suche hab' ich media_srcset jetzt als Übeltäter identifiziert.
Bei jeder Verwendung  von media_srcset bekomme ich bei einem Bildaufruf im Systemlog

` | Notice | Undefined index: height | redaxo/src/addons/media_manager/lib/effects/effect_resize.php | 57`

Getestet auch in einer frischen Installation ohne Templates oder anderem Zeug. Einfach nur Redaxo mit einem mm-effekt media_srcset. Einstellungen spielen auch keine Rolle.

Zeile 57 im mm ist:
```
       if ('%' === substr(trim($this->params['height']), -1)) {
            $this->params['height'] = round($h * ((int) rtrim($this->params['height'], '%') / 100));
        }
```
Es wird scheinbar params['height'] erwartet, aber nirgendwo definiert.

**Comment by skerbis** [comment]
Schau mal in die original Resort class vom mediamanager 😀 Vielleicht hat sich da was verändert?

**Comment by skerbis** [comment]
@marcohanke bitte mal die aktuelle GitHub-Version testen

**Comment by skerbis** [comment]
die Standardbreite muss abgegeben werden. Ich weiß nicht wie man das erzwingen kann
