### ISSUE TITLE
Helper Funktion 

### ISSUE THREAD

**Issue by eaCe** [FriendsOfREDAXO/media_srcset#29]
Ich weiß nicht ob das auch für andere relevant wäre, aber ich mag diesen halb `<img/>` halb PHP mix nicht so ganz, deswegen habe ich mir eine kleine Funktion gebastelt... 
Diese kann dann so z.B. aufgerufen werden:
`::getImgTag(REX_MEDIA[1], 'content_image', ['class' => 'lazy img-fluid w-100 h-100 position-absolute object-fit-cover', 'alt' => 'Alt overwrite'])`

```php
public static function getImgTag(string $fileName, string $mediaType, array $attributes = null) {
    $srcsets = static::getSrcSetByMediaType($mediaType);
    $srcsetsFlattened = static::flattenSrcSetArray($srcsets);
    $srcset = join(', ', $srcsetsFlattened);
    $srcset = str_replace(['{rex_media_file}','%7Brex_media_file%7D'], $fileName, $srcset);
    $media = \rex_media::get($fileName);
    $mediaSrc = \rex_media_manager::getUrl($mediaType, $fileName);
    $imageSize = getimagesize(\rex_path::addonCache('media_manager', $mediaType.'/'.$fileName));

    if(!$attributes) {
        $attributes = [];
    }

    $attributes['src'] = $mediaSrc;
    $attributes['srcset'] = $srcset;
    $attributes['width'] = $imageSize[0];
    $attributes['height'] = $imageSize[1];

    if(empty($attributes['alt'])) {
        $attributes['alt'] = $media->getValue('title');
    }

    $attributesString = implode(' ', array_map(
        function ($v, $k) {
            return $k.'="'.$v.'"';
        },
        $attributes,
        array_keys($attributes)
    ));

    echo '<img '.$attributesString.'/>';
}
```

Falls interesse besteht kann ich eien PR öffnen oder jemand übernimmt das einfach.

**Comment by skerbis** [comment]
Gerne @eaCe

**Comment by eaCe** [comment]
`echo rex_media_srcset::getImgTag(REX_MEDIA[1], 'content', ['class' => 'rounded-xl max-w-full h-auto']);`

**Comment by olien** [comment]
👍

**Comment by skerbis** [comment]
@eaCe kannst es noch für das picture Tag machen?

**Comment by eaCe** [comment]
@skerbis https://github.com/eaCe/media_srcset/commit/8e6e2a7728506703bcfc604c9a1a3e21053bce17
Ich muss noch überlegen wie ich das media Attribut hinzufüge.

**Comment by eaCe** [comment]
Habe es nun so gelöst:

```php
echo rex_media_srcset::getPictureTag(
    'redaxo.jpg',
    'content',
    ['class' => 'border-2 border-primary-500'],
    ['(min-width: 25.25em)' => 'content_small']
);
```

`getPictureTag(string $fileName, string $mediaType, array $attributes = null, array $mediaQueries = null)`

Das wäre also Media Query => Media Type

Wenn das passt erstelle ich den PR.

**Comment by eaCe** [comment]
Ich habe mir noch erlaubt #21 und #23 zu bearbeiten. #26 kann ich nicht reproduzieren.

**Comment by skerbis** [comment]
Aber liebend gerne her mit dem PR 👍🏻

**Comment by skerbis** [comment]
Danke schön @eaCe
