### ISSUE TITLE
Release herunterladen und entpacken.

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/media_srcset#3]
Aus der Readme

> Release herunterladen und entpacken.

https://github.com/FriendsOfREDAXO/media_manager_srcset/releases

Es sind aktuell keine Releases vorhanden.

**Comment by schuer** [comment]
Passend dazu: #5

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/media_srcset/releases
