### ISSUE TITLE
Eingabe via /images/mediaType/mediaFile.jpg

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/media_srcset#4]
Wie müsste man das srcset-Attribut notieren, damit das Plugins den Output korrekt erstellt.

Ist es derzeit überhaupt möglich?

**Comment by skerbis** [comment]
Das würde mir sehr gefallen.

**Comment by hirbod** [comment]
#6

**Comment by hirbod** [comment]
Hat sich mit https://github.com/FriendsOfREDAXO/media_manager_srcset/commit/58fbf92c427124899df0d393a495814569847c59 erledigt. Ich close das dann!
